"""Sigma rule generator — Feb 2026.

Converts a NivXRay analysis result (LOLBAS binaries + MITRE techniques + IOCs
+ decoded command lines) into a paste-ready **Sigma YAML detection rule**.
Analysts drop the output straight into Splunk / Sentinel / Elastic / Chronicle
via the Sigma converter (`sigmac`).

Deterministic — no LLM required. Rule quality scales with what the decoder
already extracted, so it's zero marginal cost per investigation.
"""
from __future__ import annotations
import hashlib
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


_MITRE_TACTIC = {
    "T1059":     "execution",       "T1059.001": "execution",
    "T1059.003": "execution",       "T1059.005": "execution",
    "T1078":     "defense_evasion", "T1078.002": "defense_evasion",
    "T1021":     "lateral_movement","T1021.006": "lateral_movement",
    "T1105":     "command_and_control",
    "T1218":     "defense_evasion", "T1218.010": "defense_evasion",
    "T1218.011": "defense_evasion",
    "T1140":     "defense_evasion",
    "T1562.001": "defense_evasion", "T1562.004": "defense_evasion",
    "T1555":     "credential_access","T1555.003": "credential_access",
    "T1555.004": "credential_access",
    "T1518.001": "discovery",
    "T1057":     "discovery",  "T1082": "discovery", "T1049": "discovery",
    "T1071":     "command_and_control", "T1071.001": "command_and_control",
    "T1027":     "defense_evasion",
    "T1204.002": "execution",
}


def _rule_id(seed: str) -> str:
    """Stable UUID-ish id from a payload hash so re-generating same input
    produces the same rule id."""
    h = hashlib.sha256(seed.encode("utf-8", errors="ignore")).hexdigest()
    return f"{h[0:8]}-{h[8:12]}-{h[12:16]}-{h[16:20]}-{h[20:32]}"


def emit_sigma(
    payload: str,
    output: str,
    mitre: List[Any],
    lolbas: List[Any],
    iocs: Dict[str, List[Any]],
    verdict: Optional[Dict[str, Any]] = None,
    title: Optional[str] = None,
) -> str:
    """Build a Sigma YAML string. Never raises — always returns a valid rule."""
    v = verdict or {}
    tids = sorted({(m.get("id") if isinstance(m, dict) else str(m)) for m in (mitre or [])
                   if (m.get("id") if isinstance(m, dict) else m)})
    tactics = sorted({_MITRE_TACTIC.get(t, "execution") for t in tids})
    binaries = sorted({(b.get("name") if isinstance(b, dict) else str(b)).lower()
                       for b in (lolbas or []) if b})
    urls    = [str(u) for u in (iocs.get("urls")    or [])[:5] if u]
    ips     = [str(i) for i in (iocs.get("ips")     or [])[:5] if i]
    domains = [str(d) for d in (iocs.get("domains") or [])[:5] if d]
    hashes  = [str(h) for h in (iocs.get("hashes")  or [])[:5] if h]

    rid = _rule_id(payload + "|" + output)
    now = datetime.now(timezone.utc).strftime("%Y/%m/%d")
    conf = int((v.get("confidence") or 70))
    level = ("high" if conf >= 85 else "medium" if conf >= 60 else "low")

    lines: List[str] = []
    lines.append(f"title: {title or 'NivXRay detection · ' + (v.get('summary') or 'suspicious command-line pattern')[:70]}")
    lines.append(f"id: {rid}")
    lines.append("status: experimental")
    lines.append(f"description: Auto-generated by NivXRay from a real decoded payload. Verdict: {v.get('verdict') or 'Suspicious'} ({conf}%).")
    lines.append("references:")
    for tid in tids:
        lines.append(f"  - https://attack.mitre.org/techniques/{tid.replace('.', '/')}/")
    lines.append("author: NivXRay Auto-Sigma")
    lines.append(f"date: {now}")
    lines.append("logsource:")
    lines.append("  product: windows")
    lines.append("  category: process_creation")
    lines.append("detection:")
    lines.append("  selection_image:")
    if binaries:
        lines.append("    Image|endswith:")
        for b in binaries:
            lines.append(f"      - '\\\\{b}'")
    else:
        lines.append("    Image|endswith:")
        lines.append("      - '\\\\powershell.exe'")
        lines.append("      - '\\\\cmd.exe'")
    # Extract discriminating tokens from decoded output (short, uppercase-ish)
    tokens = _discriminating_tokens(output)
    if tokens:
        lines.append("  selection_cli:")
        lines.append("    CommandLine|contains|all:")
        for t in tokens[:6]:
            safe = t.replace("'", "''")
            lines.append(f"      - '{safe}'")
    if urls or ips or domains:
        lines.append("  selection_c2:")
        if urls:
            lines.append("    CommandLine|contains:")
            for u in urls: lines.append(f"      - '{u}'")
        if ips:
            lines.append("    DestinationIp:")
            for i in ips: lines.append(f"      - '{i}'")
        if domains:
            lines.append("    DestinationHostname:")
            for d in domains: lines.append(f"      - '{d}'")
    if hashes:
        lines.append("  selection_hash:")
        lines.append("    Hashes|contains:")
        for h in hashes: lines.append(f"      - '{h}'")
    conds = ["selection_image"]
    if tokens: conds.append("selection_cli")
    if urls or ips or domains: conds.append("selection_c2")
    if hashes: conds.append("selection_hash")
    lines.append(f"  condition: {' and '.join(conds)}")
    lines.append("fields:")
    lines.append("  - Image")
    lines.append("  - CommandLine")
    lines.append("  - ParentImage")
    lines.append("  - User")
    if urls or ips or domains: lines.append("  - DestinationIp")
    lines.append("falsepositives:")
    lines.append("  - Legitimate administrative use of the same LOLBAS binaries — validate by ParentImage + User context.")
    lines.append(f"level: {level}")
    lines.append("tags:")
    for t in tids:
        lines.append(f"  - attack.{t.lower()}")
    for tac in tactics:
        lines.append(f"  - attack.{tac}")
    return "\n".join(lines) + "\n"


def _discriminating_tokens(text: str) -> List[str]:
    """Pull 4-12 char tokens from the decoded output that are LIKELY to appear
    in real telemetry (cmdlets, LOLBIN flags, file paths). Excludes plain
    English + very short tokens. Deterministic."""
    if not text:
        return []
    import re as _re
    # Prefer CLI-shaped tokens: -Flag, cmdlet-noun, /switch, backslash paths
    cands: List[str] = []
    cands += _re.findall(r"-[A-Z][a-zA-Z]{3,20}", text)
    cands += _re.findall(r"\b[A-Z][a-z]+-[A-Z][a-zA-Z]{2,20}", text)
    cands += _re.findall(r"/[a-z]{2,15}(?=\s|$)", text)
    cands += _re.findall(r"[a-zA-Z]:\\[A-Za-z0-9_\\.]{5,30}", text)
    cands += _re.findall(r"\bHK(?:LM|CU|CR)\\[A-Za-z0-9_\\]{5,40}", text)
    # Deduplicate, keep insertion order, cap length
    seen, out = set(), []
    for c in cands:
        c = c.strip()
        if 4 <= len(c) <= 60 and c not in seen:
            seen.add(c)
            out.append(c)
    return out
