"""Performance Baseline CI Gate — two-tier regression detection.

Locked with SOC user 2026-07-27.

Compares the CURRENT run of the crypto corpus against the last-known
baseline (`tests/reports/phase2_batch2_perf.json`) and enforces:

    • WARNING band  · p95 regression > 10% (visible, does not fail)
    • FAILURE band  · p95 regression > 20% (blocks merge)

The baseline itself is REGENERATED by
`test_phase2_performance_gates` — so a deliberate improvement gets
picked up on the next run. This gate protects against silent
regressions between deliberate baseline updates.
"""
from __future__ import annotations

import json
import statistics
import sys
import time
import warnings
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from v2.semantic.ps_deobfuscate import deobfuscate           # noqa: E402
from tests.corpus.phase2_crypto_samples import all_phase2_crypto_samples  # noqa: E402
from tests.corpus.phase2_aes_samples    import all_phase2_aes_samples     # noqa: E402


WARN_THRESHOLD = 0.10   # +10 % p95 regression → WARN
FAIL_THRESHOLD = 0.20   # +20 % p95 regression → FAIL
# Absolute-time floor. Below this the corpus is so fast that normal
# system jitter can easily produce 20-100 % percentage swings that
# aren't real regressions. Skip percentage comparisons below the
# floor and rely on the periodic baseline regeneration.
MIN_ABSOLUTE_MS_FOR_GATE = 5.0

BASELINE_PATH = Path(__file__).resolve().parent / "reports" / "phase2_batch2_perf.json"


def _measure_p95(cmdline: str) -> float:
    latencies = []
    for _ in range(11):
        t0 = time.perf_counter()
        deobfuscate(cmdline)
        latencies.append((time.perf_counter() - t0) * 1000.0)
    latencies.sort()
    return latencies[10]


def test_perf_baseline_ci_gate() -> None:
    """Compare current p95 against the frozen baseline. Two-tier:
    warn on >10 %, fail on >20 %."""
    if not BASELINE_PATH.exists():
        pytest.skip("baseline JSON not yet generated — run the "
                     "phase2_batch2_regression suite first")
    baseline = json.loads(BASELINE_PATH.read_text())
    per_sample_baseline = baseline.get("per_sample") or {}

    all_samples = list(all_phase2_crypto_samples()) + list(all_phase2_aes_samples())
    failures: list[str] = []
    warnings_list: list[str] = []

    for s in all_samples:
        bl = per_sample_baseline.get(s.id)
        if not bl:
            # New sample — no baseline yet. Skip silently; will be
            # captured on the next baseline regeneration.
            continue
        baseline_p95 = float(bl.get("p95_ms") or 0.0)
        if baseline_p95 < MIN_ABSOLUTE_MS_FOR_GATE:
            # Baseline is faster than the noise floor — percentage
            # comparisons are meaningless at this magnitude (0.1 ms
            # jitter → 100 % swing). Skip.
            continue
        current_p95 = _measure_p95(s.cmdline)
        delta = (current_p95 - baseline_p95) / baseline_p95
        if delta > FAIL_THRESHOLD:
            failures.append(
                f"[{s.id}] p95 regressed {delta * 100:.1f}% "
                f"(baseline={baseline_p95:.2f}ms → current={current_p95:.2f}ms)")
        elif delta > WARN_THRESHOLD:
            warnings_list.append(
                f"[{s.id}] p95 regressed {delta * 100:.1f}% (WARNING band; "
                f"baseline={baseline_p95:.2f}ms → current={current_p95:.2f}ms)")

    for msg in warnings_list:
        warnings.warn(msg, category=UserWarning, stacklevel=2)

    assert not failures, (
        f"Performance regression FAIL band (>{FAIL_THRESHOLD * 100:.0f}%) — "
        f"{len(failures)} sample(s):\n  " + "\n  ".join(failures))
