/**
 * E2E-UX0 · Wave 1 DESIGN-STATE fixtures for the Cortex-reference workspace.
 *
 * Not production data. Never persisted. Badged DESIGN-STATE in the UI.
 * Fields NivXRay cannot compute authoritatively are `null` on purpose so the
 * component renders an honest absence in the reference position.
 */

export const QUEUE = [
  { id: "INC-2912", severity: "medium", score: null, assignee: null, state: "Resolved - Other",
    updated: "Updated 3 days ago", host: "10.208.212.1", user: null, alerts: 2, hosts: 1, users: 0,
    techniques: 1, openDays: 3, created: "Jun 11 2026 09:14:02",
    title: "'Suspicious Abnormal RPC Request Found' generated by network sensor detected on host 10.208.212.1",
    sentence: "'Suspicious Abnormal RPC Request' along with 1 other detection generated by the network sensor on host 10.208.212.1.",
    userList: [] },
  { id: "INC-2913", severity: "medium", score: null, assignee: null, state: "Resolved - Other",
    updated: "Updated 3 days ago", host: "10.208.81.137", user: null, alerts: 2, hosts: 1, users: 0,
    techniques: 1, openDays: 5, created: "Jun 09 2026 22:41:55",
    title: "'Port Scan' along with 1 other detection generated by analytics detected on host 10.208.81.137",
    sentence: "'Port Scan' along with 1 other detection generated by analytics on host 10.208.81.137.",
    userList: [] },
  { id: "INC-2916", severity: "critical", score: null, assignee: "a.rahman", state: "In progress",
    updated: "Updated a few seconds ago", host: "FIN-WS-014", user: "nivxray\\a.silva",
    alerts: 4, hosts: 1, users: 2, techniques: 2, openDays: 1, created: "Jun 14 2026 09:22:11",
    title: "'Behavioral Threat' along with 3 other detections generated by Sysmon, EDR and DNS telemetry detected on host FIN-WS-014 involving 2 users",
    sentence: "'Behavioral Threat' along with 3 other detections generated by Sysmon, EDR and DNS telemetry detected on host FIN-WS-014 involving 2 users.",
    userList: ["nivxray\\a.silva", "a.silva@nivxray.io"] },
  { id: "INC-2919", severity: "high", score: null, assignee: null, state: "New",
    updated: "Updated a few seconds ago", host: "pc04", user: "pc04\\administrator",
    alerts: 2, hosts: 1, users: 1, techniques: 1, openDays: 0, created: "Jun 14 2026 11:02:39",
    title: "2 'credential access' detections generated by EDR on host pc04 involving user pc04\\administrator",
    sentence: "2 'credential access' detections generated by EDR on host pc04 involving user pc04\\administrator.",
    userList: ["pc04\\administrator"] },
  { id: "INC-2915", severity: "high", score: null, assignee: "a.rahman", state: "New",
    updated: "Updated 7 days ago", host: "10.208.212.10", user: null, alerts: 3, hosts: 1, users: 0,
    techniques: 1, openDays: 7, created: "Jun 07 2026 14:08:20",
    title: "3 'DNS overflow vulnerability' detections prevented by the network sensor on host 10.208.212.10",
    sentence: "3 'DNS overflow vulnerability' detections prevented by the network sensor on host 10.208.212.10.",
    userList: [] },
];

/** ATT&CK enterprise tactic order, as the reference strip renders it. */
export const TACTICS = [
  { key: "recon",      label: "Reconnaissance",      n: 0 },
  { key: "resdev",     label: "Resource Development", n: 0 },
  { key: "initial",    label: "Initial Access",      n: 0 },
  { key: "execution",  label: "Execution",           n: 2 },
  { key: "persist",    label: "Persistence",         n: 0 },
  { key: "privesc",    label: "Privilege Escalation", n: 0 },
  { key: "evasion",    label: "Defense Evasion",     n: 1 },
  { key: "credaccess", label: "Credential Access",   n: 0 },
  { key: "discovery",  label: "Discovery",           n: 0 },
  { key: "lateral",    label: "Lateral Movement",    n: 0 },
  { key: "collection", label: "Collection",          n: 0 },
  { key: "c2",         label: "Command and Control", n: 0 },
  { key: "exfil",      label: "Exfiltration",        n: 0 },
  { key: "impact",     label: "Impact",              n: 0 },
];

export const LIFECYCLE = [
  { key: "created",       label: "Created",          at: "Jun 14 2026 09:22:11" },
  { key: "alert",         label: "Last detection",   at: "Jun 14 2026 09:23:05" },
  { key: "assigned",      label: "Assigned",         at: "Jun 14 2026 09:41:19" },
  { key: "investigation", label: "Investigation",    at: "Jun 14 2026 10:04:52" },
  { key: "response",      label: "Response",         at: "Jun 14 2026 10:12:44" },
  { key: "resolved",      label: "Resolved",         at: null },
];

export const ALERT_SEV = [
  { k: "high",   label: "High",   n: 2 },
  { k: "medium", label: "Medium", n: 2 },
];

export const SOURCES = [
  { k: "Sysmon", n: 2 },
  { k: "EDR",    n: 1 },
  { k: "DNS",    n: 1 },
];

/**
 * All TEN NivXRay investigation capabilities. The Cortex reference shows five
 * tabs; reducing NivXRay to five would delete capability to gain visual
 * similarity, which the owner directive forbids.
 */
export const WS_TABS = [
  { key: "overview",   label: "Overview",     wave: 1, ref: "Cortex XDR incident Overview" },
  { key: "story",      label: "Attack Story", count: 4, wave: 2, ref: "Microsoft Defender XDR Attack story (3-pane)" },
  { key: "timeline",   label: "Timeline",     wave: 2, ref: "Cortex XDR incident Timeline" },
  { key: "evidence",   label: "Evidence",     count: 6, wave: 2, ref: "Cisco XDR Evidence tab" },
  { key: "entities",   label: "Entities",     count: 3, wave: 2, ref: "Cortex XDR Key Assets & Artifacts" },
  { key: "detections", label: "Detections",   count: 4, wave: 2, ref: "Cisco XDR Detection tab" },
  { key: "mitre",      label: "MITRE",        wave: 2, ref: "Cortex XDR ATT&CK strip + matrix drill-down" },
  { key: "response",   label: "Response",     wave: 4, ref: "Cortex XDR / Defender action centre" },
  { key: "activity",   label: "Activity",     count: 4, wave: 2, ref: "Cisco XDR Worklog / Defender Activities" },
  { key: "report",     label: "Report",       wave: 3, ref: "Cisco XDR Report tab" },
];
