"""Stage-1 T1 Golden-Capture harness.

Purpose
-------
Freeze the current byte-shape of five contract-critical paths BEFORE
any Stage-1 IUE code is written, so that Lane-A wiring (with
`IUE_STRUCTURED_LANE=off`) can be proven byte-identical by regression.

Modes
-----
- Default (assertion mode): read the JSON golden from ``goldens/`` and
  assert the captured object matches exactly (after volatile-field
  scrubbing).  Fails loudly if the file is missing or drifted.

- Capture mode: set the env var ``T1_GOLDEN_UPDATE=1`` and re-run to
  (over)write the golden files.  Only ever run in capture mode on
  the current ``main`` before Stage-1 IUE code is introduced.

Volatile-field scrubbing
------------------------
Timestamps, autogenerated IDs, absolute paths, and process-local
random values are replaced with sentinel strings so goldens remain
stable across runs.
"""
from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Any


_GOLDENS_DIR = Path(__file__).resolve().parent / "goldens"


# ── volatile-field scrubber ────────────────────────────────────────
_ISO_RE = re.compile(
    r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:?\d{2})?$"
)
# Provenance lineage entries are ``<engine>:<iso_timestamp>`` — strip the
# timestamp so lineage shape can be compared across runs.
_ENGINE_TS_RE = re.compile(
    r"^([a-zA-Z0-9_.\-]+):\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}"
    r"(?:\.\d+)?(?:Z|[+-]\d{2}:?\d{2})?$"
)
_HEX_ID_RE = re.compile(r"^[0-9a-f]{8,64}$")
_SES_ID_RE = re.compile(r"^ses[-_][0-9a-f]{6,}$")
_UUID_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
)

_VOLATILE_KEYS = {
    "created_at", "at", "matched_at", "started_at", "finished_at",
    "session_id", "correlation_id", "input_id", "content_fingerprint",
    "duration_ms", "processing_time_ms",
}


def _scrub_value(v: Any) -> Any:
    if isinstance(v, str):
        if _ISO_RE.match(v):
            return "<ISO_TIMESTAMP>"
        m = _ENGINE_TS_RE.match(v)
        if m:
            return f"{m.group(1)}:<ISO_TIMESTAMP>"
        if _UUID_RE.match(v):
            return "<UUID>"
        if _SES_ID_RE.match(v):
            return "<SESSION_ID>"
        if _HEX_ID_RE.match(v) and len(v) in (8, 12, 16, 24, 32, 40, 64):
            return f"<HEX_ID:{len(v)}>"
        return v
    if isinstance(v, dict):
        return {k: (_scrub_value(x) if k not in _VOLATILE_KEYS
                    else f"<VOLATILE:{k}>")
                for k, x in v.items()}
    if isinstance(v, list):
        return [_scrub_value(x) for x in v]
    return v


def scrub(obj: Any) -> Any:
    """Return a deep copy of *obj* with volatile fields replaced."""
    return _scrub_value(obj)


# ── golden IO ──────────────────────────────────────────────────────
def _golden_path(name: str) -> Path:
    _GOLDENS_DIR.mkdir(parents=True, exist_ok=True)
    return _GOLDENS_DIR / f"{name}.json"


def compare_or_capture(name: str, obj: Any) -> None:
    """Assertion helper.

    - If ``T1_GOLDEN_UPDATE=1`` → (over)write the golden file and pass.
    - Else → read the golden file and assert scrubbed equality.

    Fails with a diff hint if the golden is missing or drifted.
    """
    scrubbed = scrub(obj)
    path = _golden_path(name)

    if os.environ.get("T1_GOLDEN_UPDATE") == "1":
        path.write_text(json.dumps(scrubbed, indent=2, sort_keys=True,
                                    default=str) + "\n", encoding="utf-8")
        return

    if not path.exists():
        raise AssertionError(
            f"T1 golden {name!r} missing at {path}.  "
            f"Run `T1_GOLDEN_UPDATE=1 pytest {__file__}` from main to capture."
        )

    expected = json.loads(path.read_text(encoding="utf-8"))
    if scrubbed != expected:
        # Compact diff hint
        import difflib
        a = json.dumps(expected, indent=2, sort_keys=True).splitlines()
        b = json.dumps(scrubbed, indent=2, sort_keys=True,
                        default=str).splitlines()
        diff = "\n".join(list(difflib.unified_diff(
            a, b, fromfile=f"golden:{name}", tofile="captured", n=3))[:60])
        raise AssertionError(
            f"T1 golden drift on {name!r}.\n{diff}\n"
            f"If change is intentional and reviewed, regenerate via "
            f"`T1_GOLDEN_UPDATE=1 pytest {__file__.rsplit('/',1)[-1]}`."
        )
