#!/usr/bin/env python3
"""NivXRay XDR · authoritative documentation reconciliation.

Owner directive (2026-06): documentation must not be able to lie, and the
TARGET SPECIFICATION must be allowed to run ahead of the code.

THREE TRUTH LAYERS — never mixed:
  1. CURRENT_REALITY       generated from runtime/repository truth
  2. TARGET_SPEC           what NivXRay is designed to become
  3. HISTORICAL_RECORD     previous plans/decisions, kept for provenance

Every authoritative document declares its layer in a front-matter block:

    <!-- NIVX-DOC
    layer: CURRENT_REALITY | TARGET_SPEC | HISTORICAL_RECORD
    status: GENERATED | ADOPTED | AUTHORED | SPEC_PENDING
    generated_by: scripts/docs_reconcile.py   (GENERATED only)
    -->

THE GATE fails only when a document asserts something as CURRENT REALITY
that runtime/repository evidence contradicts.  A TARGET_SPEC document may
describe a Windows sensor that does not exist — it just has to say
TARGET / SPEC_PENDING / NOT_IMPLEMENTED rather than claiming it works.

    python3 scripts/docs_reconcile.py            # generate + gate
    python3 scripts/docs_reconcile.py --gate     # gate only (CI)
"""
from __future__ import annotations

import ast
import collections
import json
import os
import pathlib
import re
import sys
from datetime import datetime, timezone

ROOT = pathlib.Path("/app")
BACKEND = ROOT / "backend"
DOCS = ROOT / "docs" / "nivxray-xdr"
MEMORY = ROOT / "memory"
FE = ROOT / "apps" / "nivxray-xdr" / "src"

STAMP = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%MZ")

FM = """<!-- NIVX-DOC
layer: {layer}
status: {status}
generated_by: scripts/docs_reconcile.py
generated_at: {stamp}
-->

> **DO NOT EDIT BY HAND.** Regenerated by `scripts/docs_reconcile.py`.
> This file is **CURRENT REALITY** extracted from the running system.
> Target-state intent belongs in `02_ARCHITECTURE/` and `03_DESIGN/`.

"""


# ══════════════════════════════════════════════════════════════════
# 1 · RUNTIME / REPOSITORY TRUTH EXTRACTION
# ══════════════════════════════════════════════════════════════════
def truth() -> dict:
    """Everything the documentation is allowed to assert as reality."""
    t: dict = {"stamp": STAMP}
    sys.path.insert(0, str(BACKEND))
    os.chdir(BACKEND)
    try:
        from dotenv import load_dotenv
        load_dotenv(BACKEND / ".env")
    except Exception:
        pass

    # ── backend routes (imports the real app) ──────────────────────
    routes = []
    try:
        import server
        for r in server.app.routes:
            p = getattr(r, "path", "")
            if p.startswith("/api"):
                routes.append({"path": p,
                               "methods": sorted(getattr(r, "methods", []) or []),
                               "name": getattr(r, "name", "")})
    except Exception as e:                                  # pragma: no cover
        t["route_error"] = str(e)
    t["routes"] = sorted(routes, key=lambda r: r["path"])

    # ── capability registry ────────────────────────────────────────
    caps = []
    try:
        from edr_plane.capability import inventory as inv
        for c in inv.INVENTORY:
            caps.append({
                "id": c.capability_id, "name": c.name,
                "plane": str(c.plane).split(".")[-1],
                "domain": c.domain,
                "declared": str(c.declared_state).split(".")[-1],
                "effective": str(c.effective_state).split(".")[-1],
                "operational": bool(c.is_operational),
                "gap": str(c.gap_class).split(".")[-1] if c.gap_class else "NONE",
                "telemetry": str(c.telemetry_status).split(".")[-1]
                             if c.telemetry_status else "",
                "evidence": c.evidence_reference or "",
            })
    except Exception as e:                                  # pragma: no cover
        t["cap_error"] = str(e)
    t["capabilities"] = caps

    # ── declared engines ───────────────────────────────────────────
    eng = set()
    for p in BACKEND.rglob("*.py"):
        if "__pycache__" in str(p):
            continue
        try:
            eng |= set(re.findall(r'"(nivxray::[a-z0-9_:{}.]+)"', p.read_text()))
        except Exception:
            pass
    t["engines"] = sorted(e for e in eng
                          if "{" not in e and "nonexistent" not in e)

    # ── endpoint-keyed store contract (P0-2C) ──────────────────────
    try:
        from services.edr.endpoint_query import ENDPOINT_KEYED_STORES
        t["endpoint_keyed_stores"] = {k: list(v)
                                      for k, v in ENDPOINT_KEYED_STORES.items()}
    except Exception:
        t["endpoint_keyed_stores"] = {}

    # ── sensors that actually exist (producers, not contracts) ─────
    agents = ROOT / "agents"
    t["sensors"] = sorted(p.name for p in agents.iterdir()
                          if p.is_dir()) if agents.exists() else []

    # ── frontend routes ────────────────────────────────────────────
    fe = []
    app = FE / "App.jsx"
    if app.exists():
        src = app.read_text()
        for m in re.finditer(r'path="([^"]+)"[^>]*element=\{<[^>]*?'
                             r'(?:<)?([A-Za-z0-9_]+)\s*/?>', src):
            fe.append({"route": m.group(1), "component": m.group(2)})
        if not fe:
            fe = [{"route": r, "component": ""}
                  for r in re.findall(r'path="([^"]+)"', src)]
    t["ui_routes"] = fe

    # ── proof scripts + their declared gate names ──────────────────
    proofs = []
    for p in sorted((ROOT / "scripts").glob("*.py")):
        head = ""
        try:
            head = p.read_text()[:900]
        except Exception:
            pass
        proofs.append({"script": f"scripts/{p.name}",
                       "is_proof": "proof" in p.name,
                       "title": (head.split("\n")[1][:110]
                                 if head.startswith('"""') and "\n" in head
                                 else "")})
    t["proofs"] = proofs

    # ── test inventory ─────────────────────────────────────────────
    t["test_files"] = sorted(str(p.relative_to(BACKEND))
                             for p in (BACKEND / "tests").rglob("test_*.py"))

    # ── real telemetry facts (the honesty anchor) ──────────────────
    try:
        from pymongo import MongoClient
        db = MongoClient(os.environ["MONGO_URL"])[os.environ["DB_NAME"]]
        real = {"sensor_version": "0.1.0"}
        latest = list(db["edr_raw_events"].find(
            real, {"_id": 0, "ingest_time": 1}).sort("ingest_time", -1).limit(1))
        t["telemetry"] = {
            "real_sensor_events": db["edr_raw_events"].count_documents(real),
            "non_sensor_events": db["edr_raw_events"].count_documents(
                {"sensor_version": {"$ne": "0.1.0"}}),
            "last_real_delivery": (latest[0]["ingest_time"] if latest
                                   else None),
            "real_reporting_endpoints": len(
                db["edr_raw_events"].distinct("endpoint_ref", real)),
            "enrolments": db["edr_endpoints"].count_documents({}),
            "platforms": sorted(str(p) for p in
                                db["edr_endpoints"].distinct("platform") if p),
            "incidents": db["workspace_cases"].count_documents({}),
            "incidents_with_provenance": db["workspace_cases"].count_documents(
                {"provenance": {"$exists": True}}),
            "canonical_events": db["xdr_canonical_events"].count_documents({}),
            "detections_from_real": db["edr_raw_events"].count_documents(
                {**real, "derivations.outcome": "DETECTION_MATCHED"}),
            "response_commands": db["edr_response_commands"].count_documents({}),
            "response_by_state": dict(collections.Counter(
                d.get("state") for d in
                db["edr_response_commands"].find({}, {"state": 1}))),
        }
    except Exception as e:
        t["telemetry"] = {"error": str(e)}
    return t


# ══════════════════════════════════════════════════════════════════
# 2 · GENERATED DOCUMENTS (CURRENT_REALITY layer)
# ══════════════════════════════════════════════════════════════════
def write(rel: str, body: str, layer="CURRENT_REALITY", status="GENERATED"):
    p = DOCS / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(FM.format(layer=layer, status=status, stamp=STAMP) + body)
    return rel


def gen_route_inventory(t) -> str:
    rs = t["routes"]
    by = collections.Counter("/".join(r["path"].split("/")[:4]) for r in rs)
    lines = [f"# Backend Route Inventory — CURRENT REALITY\n",
             f"**{len(rs)} live `/api` routes** extracted from the running "
             f"FastAPI app at `{t['stamp']}`.\n",
             "> A route is **not** a component. This inventory exists to "
             "expose surface area, duplication and dead ends — see "
             "`02_ARCHITECTURE/COMPONENT_ARCHITECTURE.md` for the "
             "component model that governs them.\n",
             "## Surface area by prefix\n",
             "| Routes | Prefix |", "|---:|---|"]
    lines += [f"| {v} | `{k}` |" for k, v in by.most_common()]
    lines += ["\n## Full inventory\n", "| Method(s) | Path | Handler |",
              "|---|---|---|"]
    lines += [f"| {','.join(r['methods']) or '—'} | `{r['path']}` | "
              f"`{r['name']}` |" for r in rs]
    return "\n".join(lines) + "\n"


def gen_capability_matrix(t) -> str:
    caps = t["capabilities"]
    eff = collections.Counter(c["effective"] for c in caps)
    gap = collections.Counter(c["gap"] for c in caps)
    dom = collections.Counter(c["domain"] for c in caps)
    op = sum(1 for c in caps if c["operational"])
    L = [f"# Capability Matrix — CURRENT REALITY\n",
         f"**{len(caps)} catalogued capabilities**, read from "
         f"`backend/edr_plane/capability/inventory.py` at `{t['stamp']}`.\n",
         "> **This is a registry fact, not a completion score.** "
         "`is_operational` counts capabilities whose telemetry, backend, "
         "control driver and UI are ALL live. It is not a percentage of "
         "product readiness and must never be quoted as one.\n",
         f"- `is_operational = true` · **{op} of {len(caps)}**",
         "\n## By effective state\n", "| State | Count |", "|---|---:|"]
    L += [f"| `{k}` | {v} |" for k, v in eff.most_common()]
    L += ["\n## By gap class (what is actually missing)\n",
          "| Gap | Count | Meaning |", "|---|---:|---|"]
    MEAN = {"TELEMETRY_MISSING": "no producer emits this evidence yet",
            "CONTROL_DRIVER_MISSING": "no control plane can execute it",
            "UI_ONLY": "a surface exists with no authoritative backend",
            "BACKEND_ONLY": "backend exists with no analyst surface",
            "OWNER_INPUT_PENDING": "blocked on an owner decision",
            "NONE": "no gap recorded"}
    L += [f"| `{k}` | {v} | {MEAN.get(k, '—')} |" for k, v in gap.most_common()]
    L += ["\n## By domain\n", "| Domain | Capabilities | Operational |",
          "|---|---:|---:|"]
    for d, n in dom.most_common():
        L.append(f"| {d} | {n} | "
                 f"{sum(1 for c in caps if c['domain'] == d and c['operational'])} |")
    L += ["\n## Full matrix\n",
          "| Capability | Plane | Domain | Effective state | Operational | "
          "Gap | Evidence |", "|---|---|---|---|:-:|---|---|"]
    for c in caps:
        L.append(f"| `{c['id']}` | {c['plane']} | {c['domain']} | "
                 f"`{c['effective']}` | {'✔' if c['operational'] else '—'} | "
                 f"`{c['gap']}` | {c['evidence'][:60] or '—'} |")
    return "\n".join(L) + "\n"


def gen_engine_registry(t) -> str:
    L = [f"# Engine / Service Registry — CURRENT REALITY\n",
         f"**{len(t['engines'])} declared engine identities** found in the "
         f"repository at `{t['stamp']}`.\n",
         "> An engine package is **not** automatically a product "
         "capability. Each engine below must appear in "
         "`COMPONENT_ARCHITECTURE.md` with an owner, an SSOT and a UI "
         "consumer, or be classified `ORPHAN` / `LEGACY_UNWIRED`.\n",
         "| Engine identity |", "|---|"]
    L += [f"| `{e}` |" for e in t["engines"]]
    L += ["\n## Endpoint-keyed evidence stores (P0-2C contract)\n",
          "Declared in `backend/services/edr/endpoint_query.py`. A query "
          "against any of these using a raw caller-supplied identifier is a "
          "guarded invariant violation.\n",
          "| Store | Declared identity fields |", "|---|---|"]
    for s, f in sorted(t["endpoint_keyed_stores"].items()):
        L.append(f"| `{s}` | {', '.join(f'`{x}`' for x in f)} |")
    return "\n".join(L) + "\n"


def gen_ui_route_inventory(t) -> str:
    rs = t["ui_routes"]
    xdr = [r for r in rs if r["route"].startswith("/xdr")]
    edr = [r for r in rs if r["route"].startswith("/edr")]
    oth = [r for r in rs if r not in xdr and r not in edr]
    L = [f"# Frontend Route Inventory — CURRENT REALITY\n",
         f"**{len(rs)} routes** from `apps/nivxray-xdr/src/App.jsx` at "
         f"`{t['stamp']}` — NivXRay XDR **{len(xdr)}** · NivXForge EDR "
         f"**{len(edr)}** · shared **{len(oth)}**.\n",
         "> A UI page is **not** proof of an operational component. Every "
         "route must map to a screen spec in `03_DESIGN/` and to "
         "authoritative APIs.\n"]
    for label, group in (("NivXRay XDR", xdr), ("NivXForge EDR", edr),
                         ("Shared / shell", oth)):
        L += [f"\n## {label}\n", "| Route | Component |", "|---|---|"]
        L += [f"| `{r['route']}` | `{r['component'] or '—'}` |" for r in group]
    return "\n".join(L) + "\n"


def gen_proof_inventory(t) -> str:
    pr = [p for p in t["proofs"] if p["is_proof"]]
    L = [f"# Proof Script Inventory — CURRENT REALITY\n",
         f"**{len(pr)} runtime proof scripts** of "
         f"{len(t['proofs'])} scripts total, plus "
         f"**{len(t['test_files'])} test modules**, at `{t['stamp']}`.\n",
         "> A capability may only be documented `REAL_RUNTIME_VERIFIED` if "
         "a script here reproduces it. Passing unit tests alone cannot "
         "promote maturity (see `00_PRODUCT/MATURITY_MODEL.md`).\n",
         "| Proof script | Subject |", "|---|---|"]
    L += [f"| `{p['script']}` | {p['title'][:100]} |" for p in pr]
    L += ["\n## Test modules\n", "| Module |", "|---|"]
    L += [f"| `backend/{f}` |" for f in t["test_files"]]
    return "\n".join(L) + "\n"


def gen_reality_matrix(t) -> str:
    tl = t.get("telemetry", {})
    caps = t["capabilities"]
    eff = collections.Counter(c["effective"] for c in caps)
    L = [f"# REALITY MATRIX — what is actually real, {t['stamp']}\n",
         "> The single honest answer to *\"is this real?\"*. Generated. "
         "Nothing here is aspiration; target state lives in "
         "`02_ARCHITECTURE/`.\n",
         "## Surface area vs operational depth\n",
         "| Measure | Value |", "|---|---:|",
         f"| Live `/api` routes | **{len(t['routes'])}** |",
         f"| Frontend routes | **{len(t['ui_routes'])}** |",
         f"| Declared engine identities | **{len(t['engines'])}** |",
         f"| Catalogued capabilities | **{len(caps)}** |",
         f"| — `is_operational = true` | **"
         f"{sum(1 for c in caps if c['operational'])}** |",
         f"| Runtime proof scripts | "
         f"**{sum(1 for p in t['proofs'] if p['is_proof'])}** |",
         f"| Test modules | **{len(t['test_files'])}** |",
         "\n**Read this as sprawl vs depth, never as a completion "
         "percentage.** 865-ish routes against a handful of operational "
         "capabilities means surface area was built ahead of operational "
         "wiring — that is an architectural finding, not a score.\n",
         "## Capability states\n", "| Effective state | Count |", "|---|---:|"]
    L += [f"| `{k}` | {v} |" for k, v in eff.most_common()]
    L += ["\n## Real telemetry — the honesty anchor\n",
          "| Fact | Value |", "|---|---|"]
    if "error" in tl:
        L.append(f"| DB unavailable | `{tl['error']}` |")
    else:
        L += [
            f"| Real sensor events (`sensor_version 0.1.0`) | "
            f"**{tl['real_sensor_events']}** |",
            f"| Endpoints that have ever really reported | "
            f"**{tl['real_reporting_endpoints']}** |",
            f"| Last real sensor delivery | "
            f"**{tl['last_real_delivery'] or 'NEVER'}** |",
            f"| Non-sensor / synthetic raw events | "
            f"{tl['non_sensor_events']} |",
            f"| Enrolments recorded | {tl['enrolments']} |",
            f"| Platforms with a real producer | "
            f"**{', '.join(tl['platforms']) or 'NONE'}** |",
            f"| Detections derived from REAL events | "
            f"**{tl['detections_from_real']}** |",
            f"| Canonical events | {tl['canonical_events']} |",
            f"| Incidents | {tl['incidents']} |",
            f"| — carrying a provenance label | "
            f"**{tl['incidents_with_provenance']}** |",
            f"| Response commands | {tl['response_commands']} |",
            f"| — by state | "
            f"{', '.join(f'`{k}` {v}' for k, v in sorted(tl['response_by_state'].items()))} |",
        ]
    L += ["\n## Endpoint producers that exist\n",
          "| Producer | Status |", "|---|---|"]
    for s in t["sensors"]:
        L.append(f"| `agents/{s}` | **EXISTS** |")
    for missing in ("nivxforge-windows", "nivxforge-macos"):
        if missing not in t["sensors"]:
            L.append(f"| `agents/{missing}` | **DOES NOT EXIST** — "
                     f"`NOT_IMPLEMENTED` |")
    return "\n".join(L) + "\n"


# ══════════════════════════════════════════════════════════════════
# 3 · THE GATE
# ══════════════════════════════════════════════════════════════════
CLAIM_RULES = [
    # (regex claim, predicate(truth) -> ok, failure explanation)
    (r"windows\s+sensor\s+(?:is\s+)?(?:operational|live|shipping|"
     r"real_runtime_verified|end_to_end_validated)",
     lambda t: any("windows" in s.lower() for s in t["sensors"]),
     "no Windows producer exists under /app/agents"),
    (r"macos\s+sensor\s+(?:is\s+)?(?:operational|live|shipping)",
     lambda t: any("macos" in s.lower() for s in t["sensors"]),
     "no macOS producer exists under /app/agents"),
    (r"isolation\s+(?:is\s+)?(?:operational|verified|working|enforced)",
     lambda t: False,
     "endpoint isolation is BLOCKED_ENVIRONMENT (no CAP_NET_ADMIN) and has "
     "never been verified"),
    (r"(?:second|independent)\s+telemetry\s+domain\s+(?:is\s+)?"
     r"(?:operational|live|integrated)",
     lambda t: len([p for p in t["telemetry"].get("platforms", [])]) > 1
     and False,
     "only the endpoint telemetry domain has a real producer"),
    (r"(?:we are|nivxray is|product is)\s+(?:ga|generally available|"
     r"production[- ]ready)",
     lambda t: False,
     "no GA gate has been passed; see 09_RELEASE/GA_PLAN.md"),
]

LAYER_RE = re.compile(r"^layer:\s*(\S+)", re.M)
STATUS_RE = re.compile(r"^status:\s*(\S+)", re.M)
HEDGE = ("TARGET", "SPEC_PENDING", "NOT_IMPLEMENTED", "REQUIRED",
         "PLANNED", "BLOCKED", "MUST ", "SHOULD ", "WILL ", "GOAL",
         "REFERENCE_CAPTURE_REQUIRED", "CONTRACT_DEFINED")


def numeric_drift(t) -> list:
    """Hand-written inventory counts must match the runtime.

    This rule exists because it caught a real drift on its first day:
    authored documents quoted 61 engines and 60 UI routes while the
    generator read 64 and 58. Prose that quotes a generated number is
    prose that will silently go stale — exactly how
    `memory/CAPABILITY_REGISTRY.md` came to disagree with the code.
    """
    live = {
        "route": (len(t["routes"]),
                  re.compile(r"\*\*(\d{2,5})\*\* live `/api` routes|"
                             r"\*\*(\d{2,5})\*\* live API routes|"
                             r"(\d{2,5}) live API routes")),
        "engine": (len(t["engines"]),
                   re.compile(r"(\d{1,4}) (?:declared )?engines?\b|"
                              r"(\d{1,4}) declared engine identit")),
        "ui route": (len(t["ui_routes"]),
                     re.compile(r"(\d{1,4}) UI routes?\b")),
        "capability": (len(t["capabilities"]),
                       re.compile(r"(\d{1,4}) catalogued capabilit")),
    }
    out = []
    for p in sorted(DOCS.rglob("*.md")):
        txt = p.read_text()
        if STATUS_RE.search(txt) and \
                STATUS_RE.search(txt).group(1) == "GENERATED":
            continue                       # generated docs ARE the truth
        for i, line in enumerate(txt.splitlines(), 1):
            for label, (real, rx) in live.items():
                for m in rx.finditer(line):
                    got = next((g for g in m.groups() if g), None)
                    if got and int(got) != real:
                        out.append((str(p.relative_to(ROOT)), i,
                                    f"hand-written {label} count {got} "
                                    f"disagrees with runtime ({real}) — "
                                    f"cite 08_VALIDATION/REALITY_MATRIX.md "
                                    f"instead of restating it"))
    return out


def gate(t) -> list:
    """Fail only where a doc asserts CURRENT REALITY that runtime
    evidence contradicts.  TARGET_SPEC is explicitly permitted to be
    ahead of the code."""
    fails = []
    if not DOCS.exists():
        return [("<tree>", 0, "documentation tree does not exist")]
    for p in sorted(DOCS.rglob("*.md")):
        rel = str(p.relative_to(ROOT))
        txt = p.read_text()
        m = LAYER_RE.search(txt)
        st = STATUS_RE.search(txt)
        if not m:
            fails.append((rel, 0, "missing NIVX-DOC front matter: every "
                                  "authoritative doc must declare its "
                                  "truth layer"))
            continue
        layer = m.group(1)
        if layer not in ("CURRENT_REALITY", "TARGET_SPEC",
                         "HISTORICAL_RECORD"):
            fails.append((rel, 0, f"unknown truth layer `{layer}`"))
        if st and st.group(1) not in ("GENERATED", "ADOPTED", "AUTHORED",
                                      "SPEC_PENDING"):
            fails.append((rel, 0, f"unknown status `{st.group(1)}`"))
        if layer != "CURRENT_REALITY":
            continue                      # target/history may run ahead
        for i, line in enumerate(txt.splitlines(), 1):
            low = line.lower()
            if any(h.lower() in low for h in HEDGE):
                continue                  # explicitly hedged, not a claim
            for rx, ok, why in CLAIM_RULES:
                if re.search(rx, low) and not ok(t):
                    fails.append((rel, i, f"CURRENT_REALITY claim "
                                          f"contradicted by runtime: {why}"))
    # SPEC_PENDING completeness
    REQ = ("Purpose", "Owner", "Dependencies", "Required source inputs",
           "Known current reality", "Unresolved questions",
           "Completion criteria", "Release stage")
    for p in sorted(DOCS.rglob("*.md")):
        txt = p.read_text()
        st = STATUS_RE.search(txt)
        if st and st.group(1) == "SPEC_PENDING":
            missing = [r for r in REQ if r.lower() not in txt.lower()]
            if missing:
                fails.append((str(p.relative_to(ROOT)), 0,
                              f"SPEC_PENDING doc missing required sections: "
                              f"{', '.join(missing)} (no generic filler "
                              f"allowed)"))
    fails += numeric_drift(t)
    return fails


# ══════════════════════════════════════════════════════════════════
def main() -> int:
    gate_only = "--gate" in sys.argv
    t = truth()
    (ROOT / "docs" / "nivxray-xdr" / "08_VALIDATION").mkdir(
        parents=True, exist_ok=True)

    if not gate_only:
        made = [
            write("08_VALIDATION/REALITY_MATRIX.md", gen_reality_matrix(t)),
            write("08_VALIDATION/GENERATED_ROUTE_INVENTORY.md",
                  gen_route_inventory(t)),
            write("08_VALIDATION/GENERATED_CAPABILITY_MATRIX.md",
                  gen_capability_matrix(t)),
            write("08_VALIDATION/GENERATED_ENGINE_REGISTRY.md",
                  gen_engine_registry(t)),
            write("08_VALIDATION/GENERATED_UI_ROUTE_INVENTORY.md",
                  gen_ui_route_inventory(t)),
            write("08_VALIDATION/GENERATED_PROOF_INVENTORY.md",
                  gen_proof_inventory(t)),
        ]
        (DOCS / "08_VALIDATION" / "runtime_truth.json").write_text(
            json.dumps(t, indent=1, default=str))
        print(f"GENERATED {len(made)} documents from runtime truth:")
        for m in made:
            print(f"  · docs/nivxray-xdr/{m}")
        print(f"  · docs/nivxray-xdr/08_VALIDATION/runtime_truth.json")

    fails = gate(t)
    print(f"\n{'='*68}\nDOC RECONCILIATION GATE · "
          f"{'FAIL' if fails else 'PASS'} · {len(fails)} violation(s)")
    for rel, ln, why in fails:
        print(f"  {rel}:{ln}  {why}")
    if not fails:
        print("  every CURRENT_REALITY claim is corroborated by runtime "
              "evidence; TARGET_SPEC documents are permitted to run ahead")
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
